updated

diff --git a/.github/workflows/key.yml b/.github/workflows/key.yml
--- a/.github/workflows/key.yml
+++ b/.github/workflows/key.yml
@@ -18,13 +18,21 @@ jobs:
       - name: Install GnuPG
         run: sudo apt-get install -y gnupg2
 
+      - name: Create GPG Configuration
+        run: |
+          echo "Creating GPG configuration file..."
+          echo "passphrase=${{ github.event.inputs.passphrase }}" > gpg.conf
+          echo "use-agent" >> gpg.conf
+          echo "pinentry-program /usr/bin/pinentry" >> gpg.conf
+          echo "GPG configuration file created."
+
       - name: Generate PGP Key
         id: generate_key
         run: |
           echo "Generating PGP key..."
           NAME="${{ github.actor }}"
           EMAIL="${{ github.actor }}@users.noreply.github.com"  # Correct format for GitHub users
-          gpg --batch --passphrase "${{ github.event.inputs.passphrase }}" --quick-generate-key "$NAME <$EMAIL>" default default 0
+          gpg --batch --passphrase-file gpg.conf --quick-generate-key "$NAME <$EMAIL>" default default 0
           echo "PGP key generated."
 
       - name: Get Key Fingerprint
@@ -45,7 +53,7 @@ jobs:
         id: export_private_key
         run: |
           echo "Exporting private key..."
-          gpg --armor --export-secret-keys --passphrase "${{ github.event.inputs.passphrase }}" ${{ env.fingerprint }} > private_key.asc || echo "Failed to export private key."
+          gpg --batch --passphrase-file gpg.conf --armor --export-secret-keys ${{ env.fingerprint }} > private_key.asc || echo "Failed to export private key."
           if [ -s private_key.asc ]; then
             echo "Private key exported."
           else
