ahs

diff --git a/.github/workflows/key.yml b/.github/workflows/key.yml
--- a/.github/workflows/key.yml
+++ b/.github/workflows/key.yml
@@ -32,7 +32,7 @@ jobs:
           echo "Generating PGP key..."
           NAME="${{ github.actor }}"
           EMAIL="${{ github.actor }}@users.noreply.github.com"  # Correct format for GitHub users
-          gpg --batch --passphrase-file gpg.conf --quick-generate-key "$NAME <$EMAIL>" default default 0
+          gpg --batch --passphrase-file gpg.conf --pinentry-mode loopback --quick-generate-key "$NAME <$EMAIL>" default default 0
           echo "PGP key generated."
 
       - name: Get Key Fingerprint
@@ -52,10 +52,10 @@ jobs:
       - name: Export Private Key
         id: export_private_key
         run: |
-          echo "Setting GPG_TTY..."
-          export GPG_TTY=$(tty || echo /dev/null)
+          echo "Disabling GPG agent..."
+          export GPG_AGENT_INFO=""
           echo "Exporting private key..."
-          gpg --batch --passphrase-file gpg.conf --armor --export-secret-keys ${{ env.fingerprint }} > private_key.asc || echo "Failed to export private key."
+          gpg --batch --passphrase-file gpg.conf --pinentry-mode loopback --armor --export-secret-keys ${{ env.fingerprint }} > private_key.asc || echo "Failed to export private key."
           if [ -s private_key.asc ]; then
             echo "Private key exported."
           else
